= Engagement Journal - Ansible Advanced Homework

== Executive Summary

MitziCom has asked to provide a Proof of Concept using Red Hat Ansible Tower, Red Hat Ansible and Red Hat Openstack to determine the feasibility of using Ansible Tower
as a CI/CD tool for automating continuous deployment of an internal three-tier application on QA and production environments.

Several playbooks and roles were created to perform a full environment configuration, to setup Tower, Openstack and AWS, and to deploy the three tier app.

== Deployment

The next sections describe step-by-step how to use every main playbook in order to perform the initial Openstack configuration, the three tier app deployment and
how to use everything in Tower.

=== Repository

To clone this repository:

[source,bash]
----
git clone git@github.com:AlmendraSalgado/ansible_advance_homework.git
cd ansible_advance_homework/
----

=== Openstack - Workstation Setup

When the environment is recently provide and it doesn't have any previous setup, the configuration to use Openstack should be done before everything else. Playbooks are
provided to help you set up the SSH keys required to connect to the Red Hat OpenStack Platform (RHOSP) environment.

Once, this repository is cloned, run the playbook site-setup-workstation.yml to provision the network, flavor, security groups and SSH keys.

[source,bash]
----
OSP_GUID=<<Openstack GUID from mail>>
ansible-playbook site-setup-workstation.yml -e OSP_GUID=${OSP_GUID} --private-key=/root/.ssh/mykey.pem -u <username-company.com>
----

The playbook will set up workstation-${OSP_GUID}.rhpds.opentlc.com as an isolated node and will set up opentstack.pem as a private key and openstack.pub as a public key
for connection between the bastion and workstation hosts.

=== OSP Instance

Once the Openstack setup is done, the next sections can be execute to create or delete instances and to perform some configurations and get a three tier app environment.

This playbooks requires the previous inventory creation to use workstation. Because it will be use it in Tower, it doesn't have this previous requirement.

==== Instance Creation

To provision RHOSP instances to support the deployment of a three-tier app using the network details and flavor specified in the previous section the playbook
should be executed as follows:

[source,bash]
----
OSP_GUID=<<Openstack GUID from mail>>
ansible-playbook site-osp-instances.yml -e OSP_GUID=${OSP_GUID} --private-key=/root/.ssh/mykey.pem -u <username-company.com>
----

This playbook uses the role called link:https://github.com/AlmendraSalgado/ansible_advance_homework/tree/master/roles/osp-servers[osp-servers].
To understand better what it does, follow the link to its README section.

==== Instance Deletion

A playbook to destroy the QA environment on RHOSP was required. In the Tower workflow, a playbook will be exevuted previuosly to test if the environment
was correctly deployed. If this test fails, the instances will be destroyed

[source,bash]
----
OSP_GUID=<<Openstack GUID from mail>>
ansible-playbook site-osp-delete.yml -e OSP_GUID=${OSP_GUID} --private-key=/root/.ssh/mykey.pem -u <username-company.com>
----

This playbook uses the role called https://github.com/AlmendraSalgado/ansible_advance_homework/tree/master/roles/osp-instance-delete[osp-instance-delete].
To understand better what it does, follow the link to its README section.

==== Three tier app configuration

The Three tier app configuration will setup 2 instances with webservices to expose through port 80, 1 load balancer which will be balancing the
load between the previous 2 instances and 1 database. This configuration will be done by executing the following:

[source,bash]
----
OSP_GUID=<<Openstack GUID from mail>>
ansible-playbook site-3tier-app.yml -e OSP_GUID=${OSP_GUID} --private-key=/root/.ssh/mykey.pem -u <username-company.com>
----

This playbook uses the following roles:

* https://github.com/AlmendraSalgado/ansible_advance_homework/tree/master/roles/osp-facts[osp-facts].
* https://github.com/AlmendraSalgado/ansible_advance_homework/tree/master/roles/lb-tier[lb-tier].
* https://github.com/AlmendraSalgado/ansible_advance_homework/tree/master/roles/app-tier[app-tier].
* https://github.com/AlmendraSalgado/ansible_advance_homework/tree/master/roles/db-tier[db-tier].

To understand better what it does, follow the link to its README section.

=== Ansible Tower Config

* From the cloned repo run `site-config-tower.yml` playbook to create job templates and workflow template.

[source,text]
----
[bastion]$ sudo -i
[bastion]# cd ansible_advance_homework
[bastion]# TOWER_GUID=<Ansible Tower Homework GUID from mail>
[bastion]# OSP_GUID=<Openstack for Ansible GUID from mail>
[bastion]# OPENTLC_LOGIN=<username-company.com>
[bastion]# OPENTLC_PASSWORD=<your openlc account password>
[bastion]# GITHUB_REPO=https://github.com/<githubhandler>/ansible_advance_homework
[bastion]# JQ_REPO_BASE=http://www.opentlc.com/download/ansible_bootcamp
[bastion]# REGION=<enter region name example us-east-1>
[bastion]# RH_MAIL_ID=<your mail id for dynamic inventory tag>
[bastion]# ansible-playbook site-config-tower.yml -e tower_GUID=${TOWER_GUID} -e osp_GUID=${OSP_GUID} -e opentlc_login=${OPENTLC_LOGIN} -e path_to_opentlc_key=/root/.ssh/mykey.pem -e param_repo_base=${JQ_REPO_BASE} -e opentlc_password=${OPENTLC_PASSWORD} -e REGION_NAME=${REGION} -e EMAIL=${RH_MAIL_ID} -e github_repo=${GITHUB_REPO}
----

=== Anexo

==== Playbooks Glosary

.List of Playbooks
[%header,cols=2*]
|===
| Files or dir | Purpose
| app-tier | Install application server role
| db-tier  | Install postgressql server for database role
| lb-tier  | Install HA proxy role
| base-config | Setup yum repo and base packages role
| setup-workstation | Setup workstation, create network, ssh keypair, security group etc. role
| osp-servers | Provision OSP Instances role
| osp-instance-delete | Delete OSP Instances role
| osp-facts | Genrate in-memory inventory for OSP instances role
| roles/config-tower/vars/main.yml | Very important file to review. All the variable values are set there. Please do not make any changes in the file
| config-tower | Role to configure ansible tower job templates and workflow
| aws_creds.yml | Fetch GUIDkey.pem from bastion of Three tier application env and create machine credential to connect to AWS instances
| aws_provision.yml | Use `order_svc.sh` script to provision env
| aws_status_check.yml | Check aws instances are up or not
| site-3tier-app.yml | Playbook to deploy three tier app
| site-install-isolated-node.yml | Playbook to install isolated node
| site-config-tower.yml | Playbook to call role `config-tower`
| site-osp-delete.yml | Playbook to call role
| site-osp-instances.yml | Playbook to call role
| site-setup-workstation.yml | Playbook to call role
| site-smoke-osp.yml | Playbook to test three tier app on OSP
| site-smoketest-aws.yml | Playbook to test three tier app on AWS
| grading-script.yml | Self grading script
| roles/config-tower/tasks/ec2_dynamic.yml | For creating Dynamic inventory in Ansible tower. Use `AWS Access Key` for credential
| roles/config-tower/tasks/job_template.yml | For creating job templates
| roles/config-tower/tasks/pre-config-tower.yml | Any pre config tasks needed
| roles/config-tower/tasks/workflow_template.yml | genrate workflow from `workflow.yml` file
| roles/config-tower/tasks/post-config-tower.yml | any post config jobs
|===
