- hosts: frontends
  gather_facts: false
  tasks:
  - name: Use Uri module for writing smoke test.
    uri:
      url: "http://{{ inventory_hostname }}"
      return_content: yes
    register: webpage
    failed_when: "'Ansible' not in webpage.content"
