---
- name: Machine Credentail to connect to workstation using openstack.pub
  tower_credential:
    tower_config_file: "{{ config_file }}"
    name: "{{ ssh_cred_name }}"
    organization: "{{ org_name }}"
    state: present
    kind: ssh
    ssh_key_data: "{{ user_cred_path }}"
    username: "{{ user_cred_name }}"

- name: Create Homework Assignment project
# Use tower module or tower-cli to create Ansible Tower project. Name of the project is specifed in ./vars/main.yml
  tower_project:
    tower_config_file: "{{ config_file }}"
    name: "{{ proj_name }}"
    description: "{{ proj_name }}"
    organization: Default
    state: present
    scm_branch: "{{ scm_branch }}"
    scm_type: git
    scm_update_on_launch: true
    scm_url: "{{ scm_url }}"

- name: Create Inventory
  tower_inventory:
    name: "{{ static_inventory_name }}"
    organization: "{{ org_name }}"
    state: present
    tower_config_file: "{{ config_file }}"

- name: Create Group in static inventory 
  tower_group:
    name: "{{ group_name }}"
    inventory: "{{static_inventory_name}}"
    state: present
    tower_config_file: "{{ config_file }}"

- name: Add workstation host in tower_inventory 
  tower_host:
    name: "{{ host_name }}"
    inventory: "{{ static_inventory_name }}"
    state: present
    tower_config_file: "{{ config_file }}"

- name: Associate workstation host to group 
  command: | 
    tower-cli host associate --host "{{host_name}}" --group "{{group_name}}"

- name: Tower Creds key file
  tower_credential:
    name: "{{ opentlc_cred_name }}"
    organization: "{{ org_name }}"
    state: present
    kind: ssh
    ssh_key_data: /root/.ssh/prv_key.pem
    username: "{{ opentlc_login }}"
    tower_config_file: "{{ config_file }}"

- name: Remove secret
  file:
    name: /root/secret.pem
    state: absent

